services:
  catalogdb:
    image: postgres

  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: CatalogApi/Dockerfile
    # args:
    #   - configuration=Debug
  
  basketdb:
    image: postgres

  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: BasketApi/Dockerfile

  distributedcache:
    image: redis


# volumes:
#   postgres_catalog:
