# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  catalogapi:
    image: catalog-api
    platform: linux/arm64
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
