services:
  catalogdb:
    image: postgres

  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: CatalogApi/Dockerfile
    # args:
    #   - configuration=Debug

# volumes:
#   postgres_catalog:
